[package]
name = "hello_world"
version = "0.1.0"
authors = ["dollarkiller <wangy@mvalley.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sincere = "0.7.0-alpha.1"